spring.application.name=Usuarios

# 1. Credenciales de la base de datos (Nota que al final de la URL dice db_usuarios)
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_usuarios
spring.datasource.username=postgres
spring.datasource.password=Conce123

# 2. Configuración para que Spring Boot cree la tabla automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. (Opcional) Para ver en la consola el SQL que Spring Boot está ejecutando por detrás
spring.jpa.show-sql=true

jwt.secret=SanosYSalvosSuperSecretKeyParaProtegerLosMicroservicios2026
jwt.expiration=86400000

server.port=8080

